[project]
name = 'community-governance'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.community-governance]
path = 'contracts/community-governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.micro-lending]
path = 'contracts/micro-lending.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
